* src worder
* files worder
* todo worder
** сделать отдельный орг
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/worder/worder-cljs-project.org")
** сделать копию проекта
* backlog worder
** заменить в разделе файлов на новый путь
** запустить копию
убедится в работо способности
** перенести в орг нужные файла для работы
взять как миннимум один фаил что убедить в работоспособности механизма
** компонет измеритель реакции
нужен новый компонет- кнопка
может быть в двух состояниях. Состояние нажатое\активное состояни не активное.
это кнопка сикундомера.
в активном она запоминает состояние в котором она была нажата
и активирует второй компонет который выводит количество прошедших секунд.
при деактивации оно высчитвает сколько секунд прошло и запоминает это значение в переменную

посуте это пример каунтера
много можно взять оттуда
(find-file-other-frame "~/Dev/ClojureScript/tutorials/my-cljs-project/keechma-counter/src/cljs/keechma_counter/ui/main.cljs")
[[file:keechma-counter/src/cljs/keechma_counter/ui/main.cljs::\[:button {:on-click #(ui/send-command ctx :dec)} "-"\]]]
** показатель последнего замера реакции
возможно не компонет а просто хикап структура
** переписать текст под слова в интервейсе
добовлем слова вместо туду
видемо вордер
** переписать текст под слова в коде
повозможно везде по коду
** добавить компонент замера в туду-итемс
у каждого туду кнопка замерить и результат последнего замера
** добавить кнопки сохранить слова 
возможно только сразу все в текст
с результатами в текстовый фаил
сохранить только завершоные
сохранить только не завершоные
сохронять те что в даный момент отфильтрованы
тоесть кнопка "сохранить активные as .txt"
тоесть либо все либо завершоные либо не завершоные
** добавить кнопки сохранить слова в цсв
возможно только сразу все в цсв
с результатами 
сохранить только завершоные
сохранить только не завершоные
сохронять те что в даный момент отфильтрованы
тоесть кнопка "сохранить активные as .csv"
тоесть либо все либо завершоные либо не завершоные
** загрузить список слов
** сменить цветовую схему
на автоматическую посмотреть что из этого получится
** забилдить для размешения
** захостить
возможно нужна будет помошь Уни
** передать вале
* 2025-11-02
** file worder-cljs-project.org
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/worder/worder-cljs-project.org")
** my-cljs-project.org
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/my-cljs-project.org")
