:PROPERTIES:
:header-args: :tangle no :mkdirp yes :results output silent :no-expand t
:END:
* src worder
** src core
** src components
*** components/app.cljs
:PROPERTIES:
:header-args: :tangle  ./src/keechma_todomvc/components/app.cljs
:END:
**** file
(find-file-other-frame "./src/keechma_todomvc/components/app.cljs")
**** src
#+begin_src clojure :no-expand t :mkdirp yes 
(ns keechma-todomvc.components.app
  "# Main app component"
  (:require [keechma-todomvc.ui :refer [<comp comp> sub>]]))

(defn render
  "## Renders the top level UI

  Some elements are rendered inline, others are implemented as
  `components`. Each `component` will have its own `context` provided.

### Component Deps

- `:new-todo` top field where new `todos` are entered
- `:toggle-todos` checkbox to the left of `:new-todo`
- `:todo-list` main body list of `todos`
- `:footer` active count, filtering, clearing

### Subscription Deps

- `:has-todos?` returns true if there are any todos in the EntityDB."
  [ctx]
  [:<>
   [:section.todoapp
    [:header.header
     [:h1 "Worder"]
     [comp> ctx :new-todo]]
    (when (sub> ctx :has-todos?)
      [:<>
       [:section.main
        [comp> ctx :toggle-todos]
        [comp> ctx :todo-list]]
       [comp> ctx :footer]])]
   [:footer.info
    [:p "Double-click to edit a word"]
    [:p
     [:a {:href "https://keechma.com"} "Keechma"] " "
     [:a {:href "http://todomvc.com"} "TodoMVC"]]]])

(def component
  (<comp :renderer render
         :component-deps [:new-todo
                          :toggle-todos
                          :todo-list
                          :footer]
         :subscription-deps [:has-todos?]))
#+end_src

* files worder
** files core
(find-file-other-frame "./src/keechma_todomvc/app.cljs")
(find-file-other-frame "./src/keechma_todomvc/subscriptions.cljs")
(find-file-other-frame "./src/keechma_todomvc/ui.cljs")
(find-file-other-frame "./src/keechma_todomvc/util.cljs")
(find-file-other-frame "./src/keechma_todomvc/components.cljs")
(find-file-other-frame "./src/keechma_todomvc/edb.cljs")
(find-file-other-frame "./src/keechma_todomvc/edb.clj")
** files components
(find-file-other-frame "./src/keechma_todomvc/components/app.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/new_todo.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/toggle_todos.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/todo_list.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/todo_item.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/todo_edit.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/footer.cljs")
** files controler
(find-file-other-frame "./src/keechma_todomvc/controllers/todos.cljs")
** files entities
(find-file-other-frame "./src/keechma_todomvc/entities/todo.cljs")
** files resurs
(find-file-other-frame "./resources/public/css/style.css")
(find-file-other-frame "./resources/public/index.html")
** files project
(find-file-other-frame "./project.clj")
(find-file-other-frame "./target/stale/leiningen.figwheel.clean-on-dependency-change")
** files other
find "$PWD" -type f >>filepath.txt

(find-file-other-frame "./README.md")
(find-file-other-frame "./figwheel_server.log")
* run worder
*** run
lein figwheel

:cljs/quit
:cljs/restart
*** clon
git clone https://github.com/keechma/example-todomvc.git
* TODO todo worder
** DONE запустить копию
убедится в работо способности
** DONE перенести в орг нужные файла для работы
взять как миннимум один фаил что убедить в работоспособности механизма
** DONE сделать комит
** переделать под фигвилл маин
*** ИИ
у меня есть проект под lein figwheel
(find-file-other-frame "./project.clj")
(defproject keechma-todomvc "0.1.0-SNAPSHOT"
  :description "TodoMVC implemented in Keechma"
  :url "http://github.com/keechma/keechma-todomvc"
  :license {:name "MIT"}

  :min-lein-version "2.5.3"

  :dependencies [[org.clojure/clojure "1.10.1"]
                 [org.clojure/clojurescript "1.10.597"]
                 [org.clojure/core.async "0.7.559"
                  :exclusions [org.clojure/tools.reader]]
                 [reagent "0.9.1"]
                 [keechma "0.3.14"
                  :exclusions [cljsjs/react-with-addons
                               cljsjs/react-dom
                               cljsjs/react-dom-server]]
                 [keechma/entitydb "0.1.6"]]

  :plugins [[lein-figwheel "0.5.19"]
            [lein-cljsbuild "1.1.7"
             :exclusions [[org.clojure/clojure]]]
            [lein-marginalia "0.9.1"]]

  :source-paths ["src"]

  :clean-targets ^{:protect false} ["resources/public/js/compiled" "target"]

  :cljsbuild
  {:builds
   [{:id "dev"
     :source-paths ["src"]
     :figwheel {:on-jsload "keechma-todomvc.app/restart!"}
     :compiler {:main                 keechma-todomvc.app
                :optimizations        :none
                :output-to            "resources/public/js/app.js"
                :output-dir           "resources/public/js/dev"
                :asset-path           "js/dev"
                :source-map-timestamp true}}
    ;; This next build is an compressed minified build for
    ;; production. You can build this with:
    ;; lein cljsbuild once min
    {:id "min"
     :source-paths ["src"]
     :compiler {:main            keechma-todomvc.app
                :optimizations   :advanced
                :output-to       "resources/public/js/app.js"
                :output-dir      "resources/public/js/min"
                :elide-asserts   true
                :closure-defines {goog.DEBUG false}
                :pretty-print    false}}]}

  :figwheel {;; :http-server-root "public" ;; default and assumes "resources"
             ;; :server-port 3449 ;; default
             ;; :server-ip "127.0.0.1"

             :css-dirs ["resources/public/css"] ;; watch and update CSS

             ;; Start an nREPL server into the running figwheel process
             ;; :nrepl-port 7888

             ;; Server Ring Handler (optional)
             ;; if you want to embed a ring handler into the figwheel http-kit
             ;; server, this is for simple ring servers, if this
             ;; doesn't work for you just run your own server :)
             ;; :ring-handler hello_world.server/handler

             ;; To be able to open files in your editor from the heads up display
             ;; you will need to put a script on your path.
             ;; that script will have to take a file path and a line number
             ;; ie. in  ~/bin/myfile-opener
             ;; #! /bin/sh
             ;; emacsclient -n +$2 $1
             ;;
             ;; :open-file-command "myfile-opener"

             ;; if you want to disable the REPL
             ;; :repl false

             ;; to configure a different figwheel logfile path
             ;; :server-logfile "tmp/logs/figwheel-logfile.log"
             })

как мне его переделать под figwheel main?
тоесть под фаил deps.edn?
так чтоб я мог его запускать как clojure -M:fig:build?
есть какойто автоматический способ сформировать ./deps.edn на основе ./project.clj?
*** команда
clojure -Sdeps '{:deps {leiningen/tools.deps.converter {:mvn/version "0.4.2"}}}' \
-m leiningen.tools.deps.converter project.clj

** сделать комит
** сделать новый фаил компонента
** сделать комит
** компонет измеритель реакции
нужен новый компонет- кнопка
может быть в двух состояниях. Состояние нажатое\активное состояни не активное.
это кнопка сикундомера.
в активном она запоминает состояние в котором она была нажата
и активирует второй компонет который выводит количество прошедших секунд.
при деактивации оно высчитвает сколько секунд прошло и запоминает это значение в переменную

посуте это пример каунтера
много можно взять оттуда
(find-file-other-frame "~/Dev/ClojureScript/tutorials/my-cljs-project/keechma-counter/src/cljs/keechma_counter/ui/main.cljs")
[[file:keechma-counter/src/cljs/keechma_counter/ui/main.cljs::\[:button {:on-click #(ui/send-command ctx :dec)} "-"\]]]
** показатель последнего замера реакции
возможно не компонет а просто хикап структура
* REPL
:PROPERTIES:
:header-args: :tangle no :mkdirp yes :results output silent :no-expand t
:END:
** start
lein figwheel
clojure -M:fig:build
#+begin_src elisp :results output silent 
(evil-previous-line)
(org-cycle)
(delete-other-windows)
(let (buffer-name-to-close (buffer-name))
        (evil-window-split)
        (eshell)
        (evil-quit)
        (switch-to-buffer-other-frame buffer-name-to-close))
#+end_src
** commans
clojure -M:fig:build
:cljs/quit
:cljs/restart

clojure -M:fig:clean
clojure -M:fig:build
* backlog worder
** переписать текст под слова в интервейсе
добовлем слова вместо туду
видемо вордер
** переписать текст под слова в коде
повозможно везде по коду
** добавить компонент замера в туду-итемс
у каждого туду кнопка замерить и результат последнего замера
** добавить кнопки сохранить слова 
возможно только сразу все в текст
с результатами в текстовый фаил
сохранить только завершоные
сохранить только не завершоные
сохронять те что в даный момент отфильтрованы
тоесть кнопка "сохранить активные as .txt"
тоесть либо все либо завершоные либо не завершоные
** добавить кнопки сохранить слова в цсв
возможно только сразу все в цсв
с результатами 
сохранить только завершоные
сохранить только не завершоные
сохронять те что в даный момент отфильтрованы
тоесть кнопка "сохранить активные as .csv"
тоесть либо все либо завершоные либо не завершоные
** загрузить список слов
** сменить цветовую схему
на автоматическую посмотреть что из этого получится
** забилдить для размешения
** захостить
возможно нужна будет помошь Уни
** передать вале
* DONE Done worder
** DONE сделать отдельный орг
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/worder/worder-cljs-project.org")
** DONE сделать копию проекта
** DONE заменить в разделе файлов на новый путь
* 2025-11-02
** file worder-cljs-project.org
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/worder/worder-cljs-project.org")
** my-cljs-project.org
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/my-cljs-project.org")
