:PROPERTIES:
:header-args: :tangle no :mkdirp yes :results output silent :no-expand t
:END:
* src worder
** src core
** src components
*** components/app.cljs
:PROPERTIES:
:header-args: :tangle  ./src/keechma_todomvc/components/app.cljs
:END:
**** file
(find-file-other-frame "./src/keechma_todomvc/components/app.cljs")
**** src
#+begin_src clojure :no-expand t :mkdirp yes 
(ns keechma-todomvc.components.app
  "# Main app component"
  (:require [keechma-todomvc.ui :refer [<comp comp> sub>]]))

(defn render
  "## Renders the top level UI

  Some elements are rendered inline, others are implemented as
  `components`. Each `component` will have its own `context` provided.

### Component Deps

- `:new-todo` top field where new `todos` are entered
- `:toggle-todos` checkbox to the left of `:new-todo`
- `:todo-list` main body list of `todos`
- `:footer` active count, filtering, clearing

### Subscription Deps

- `:has-todos?` returns true if there are any todos in the EntityDB."
  [ctx]
  [:<>
   [:section.todoapp
    [:header.header
     [:h1 "Worder"]
     [comp> ctx :new-todo]]
    (when (sub> ctx :has-todos?)
      [:<>
       [:section.main
        [comp> ctx :toggle-todos]
        [comp> ctx :todo-list]]
       [comp> ctx :footer]])]
   [:footer.info
    [:p "Double-click to edit a word"]
    [:p
     [:a {:href "https://keechma.com"} "Keechma"] " "
     [:a {:href "http://todomvc.com"} "TodoMVC"]]]])

(def component
  (<comp :renderer render
         :component-deps [:new-todo
                          :toggle-todos
                          :todo-list
                          :footer]
         :subscription-deps [:has-todos?]))
#+end_src

* files worder
** files core
(find-file-other-frame "./src/keechma_todomvc/app.cljs")
(find-file-other-frame "./src/keechma_todomvc/subscriptions.cljs")
(find-file-other-frame "./src/keechma_todomvc/ui.cljs")
(find-file-other-frame "./src/keechma_todomvc/util.cljs")
(find-file-other-frame "./src/keechma_todomvc/components.cljs")
(find-file-other-frame "./src/keechma_todomvc/edb.cljs")
(find-file-other-frame "./src/keechma_todomvc/edb.clj")
** files components
(find-file-other-frame "./src/keechma_todomvc/components/app.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/new_todo.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/toggle_todos.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/todo_list.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/todo_item.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/todo_edit.cljs")
(find-file-other-frame "./src/keechma_todomvc/components/footer.cljs")
** files controler
(find-file-other-frame "./src/keechma_todomvc/controllers/todos.cljs")
** files entities
(find-file-other-frame "./src/keechma_todomvc/entities/todo.cljs")
** files resurs
(find-file-other-frame "./resources/public/css/style.css")
(find-file-other-frame "./resources/public/index.html")
** files project
(find-file-other-frame "./project.clj")
(find-file-other-frame "./target/stale/leiningen.figwheel.clean-on-dependency-change")
** files other
find "$PWD" -type f >>filepath.txt

(find-file-other-frame "./README.md")
(find-file-other-frame "./figwheel_server.log")
* run worder
*** run
lein figwheel

:cljs/quit
:cljs/restart
*** clon
git clone https://github.com/keechma/example-todomvc.git
* TODO todo worder
** DONE запустить копию
убедится в работо способности
** DONE перенести в орг нужные файла для работы
взять как миннимум один фаил что убедить в работоспособности механизма
** сделать комит
** сделать новый фаил компонента
** сделать комит
** компонет измеритель реакции
нужен новый компонет- кнопка
может быть в двух состояниях. Состояние нажатое\активное состояни не активное.
это кнопка сикундомера.
в активном она запоминает состояние в котором она была нажата
и активирует второй компонет который выводит количество прошедших секунд.
при деактивации оно высчитвает сколько секунд прошло и запоминает это значение в переменную

посуте это пример каунтера
много можно взять оттуда
(find-file-other-frame "~/Dev/ClojureScript/tutorials/my-cljs-project/keechma-counter/src/cljs/keechma_counter/ui/main.cljs")
[[file:keechma-counter/src/cljs/keechma_counter/ui/main.cljs::\[:button {:on-click #(ui/send-command ctx :dec)} "-"\]]]
** показатель последнего замера реакции
возможно не компонет а просто хикап структура
* REPL
:PROPERTIES:
:header-args: :tangle no :mkdirp yes :results output silent :no-expand t
:END:
** start
lein figwheel
clojure -M:fig:build
#+begin_src elisp :results output silent 
(evil-previous-line)
(org-cycle)
(delete-other-windows)
(let (buffer-name-to-close (buffer-name))
        (evil-window-split)
        (eshell)
        (evil-quit)
        (switch-to-buffer-other-frame buffer-name-to-close))
#+end_src
** commans
clojure -M:fig:build
:cljs/quit
:cljs/restart

clojure -M:fig:clean
clojure -M:fig:build
* backlog worder
** переписать текст под слова в интервейсе
добовлем слова вместо туду
видемо вордер
** переписать текст под слова в коде
повозможно везде по коду
** добавить компонент замера в туду-итемс
у каждого туду кнопка замерить и результат последнего замера
** добавить кнопки сохранить слова 
возможно только сразу все в текст
с результатами в текстовый фаил
сохранить только завершоные
сохранить только не завершоные
сохронять те что в даный момент отфильтрованы
тоесть кнопка "сохранить активные as .txt"
тоесть либо все либо завершоные либо не завершоные
** добавить кнопки сохранить слова в цсв
возможно только сразу все в цсв
с результатами 
сохранить только завершоные
сохранить только не завершоные
сохронять те что в даный момент отфильтрованы
тоесть кнопка "сохранить активные as .csv"
тоесть либо все либо завершоные либо не завершоные
** загрузить список слов
** сменить цветовую схему
на автоматическую посмотреть что из этого получится
** забилдить для размешения
** захостить
возможно нужна будет помошь Уни
** передать вале
* DONE Done worder
** DONE сделать отдельный орг
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/worder/worder-cljs-project.org")
** DONE сделать копию проекта
** DONE заменить в разделе файлов на новый путь
* 2025-11-02
** file worder-cljs-project.org
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/worder/worder-cljs-project.org")
** my-cljs-project.org
(find-file-other-frame "/home/buyn/Dev/ClojureScript/tutorials/my-cljs-project/my-cljs-project.org")
